server:
  port: 8084
spring:
  application:
    name: spring-cloud-practice-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  hystrix:
    enabled: true # 開啟 hystrix 熔斷器